# Generated by Django 5.0.1 on 2024-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(default='ВЫГОДНО', max_length=30, verbose_name='Mark')),
                ('photo', models.FileField(upload_to='photos/')),
                ('service', models.CharField(max_length=100, verbose_name='Service')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Old Price')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Price')),
            ],
        ),
    ]
