# Generated by Django 5.0.1 on 2024-01-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='new_price',
            field=models.IntegerField(verbose_name='New Price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='old_price',
            field=models.IntegerField(verbose_name='Old Price'),
        ),
    ]
