# Generated by Django 4.2.1 on 2024-02-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
